version: 2
updates:
  # Update Bun dependencies (via package.json)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "wess"
    assignees:
      - "wess"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    ignore:
      # Ignore Node.js specific packages since we use Bun
      - dependency-name: "node"
      - dependency-name: "npm"
      - dependency-name: "yarn"

  # Update GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "wess"
    assignees:
      - "wess"
    commit-message:
      prefix: "ci"
      include: "scope"