name: CI

# Bun-first CI pipeline - No Node.js required
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile --no-cache

      - name: Run Biome linting
        run: bun run lint:check

      - name: Check Biome formatting
        run: bun run format:check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile --no-cache

      - name: Run tests
        run: bun test

      - name: Clean up test artifacts
        run: bun run clean:test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile --no-cache

      - name: Build all packages
        run: bun run build

      - name: Validate templates
        run: bun run validate:templates

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile --no-cache

      - name: Type check packages
        run: |
          cd packages/cli && bun run build:types
          cd ../server && bun run build:types
          cd ../auth && bun run build:types
          cd ../plugins && bun run build:types
          cd ../templates && bun run build:types