name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: read
  id-token: write

jobs:
  release:
    name: Release to NPM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile --no-cache

      - name: Run tests
        run: bun test

      - name: Lint and format check
        run: |
          bun run lint:check
          bun run format:check

      - name: Build all packages
        run: bun run build

      - name: Validate templates
        run: bun run validate:templates

      - name: Setup NPM authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

      - name: Publish to NPM
        run: bun run publish:all

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ## Changes in this Release
            
            Please see the [CHANGELOG.md](./CHANGELOG.md) for detailed changes.
            
            ## Installation
            
            ```bash
            # Install core server
            bun add @verb/server
            
            # Install CLI globally
            bun add -g @verb/cli
            
            # Install auth plugin
            bun add @verb/auth
            
            # Install all plugins
            bun add @verb/plugins
            
            # Install templates
            bun add @verb/templates
            ```
          draft: false
          prerelease: false